
[tools]
# yazi dependencies
"github:sharkdp/fd" = "10.4.2"
"github:junegunn/fzf" = "0.72.0"
"github:BurntSushi/ripgrep" = { version = "15.1.0", exe = "rg" }

# development tools
"github:JohnnyMorganz/stylua" = "2.4.1"
"github:rvben/rumdl" = "0.1.85"
actionlint = "1.7.12"
