packages:
  - ./integration-tests/
allowBuilds:
  cypress: true
  esbuild: true
saveExact: true

onlyBuiltDependencies:
  - cypress
  - esbuild
  - node-pty

minimumReleaseAgeExclude:
  - "@mikavilpas/oxfmt-config@3.0.0"
